### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by gongseli** [psal/jstylo#14]
I have maven install the project and generate jstylo-2.9.0.jar in "target" folder. However, When I run "java -jar jstylo-2.9.0.jar", there is an error that no main manifest attribute, in jstylo-2.9.0.jar.How can I solve it?

**Comment by cFire** [comment]
You can use the `mvn package` command to build the `jstylo-2.9.0-jar-with-dependencies.jar` jar. (Perhaps you can copy the jar from the `target` dir, but I haven't tried.)
Then you should be able to run with `java -Djava.ext.dirs=lib/ -jar jstylo-2.9.0-jar-with-dependencies.jar`.

**Comment by vrublack** [comment]
Thanks, this worked!

**Comment by vmrfrankie** [comment]
When I tried running java -Djava.ext.dirs=lib/ -jar jstylo-2.9.0-jar-with-dependencies.jar I got the exception: 
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: com/jgaap/generics/LanguageParsingException
        at edu.drexel.psal.jstylo.GUI.GUIMain.initData(GUIMain.java:266)
        at edu.drexel.psal.jstylo.GUI.GUIMain.<init>(GUIMain.java:259)
        at edu.drexel.psal.jstylo.GUI.GUIMain$1.run(GUIMain.java:249)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.jgaap.generics.LanguageParsingException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 17 more
